FROM edumar111/php-base:1.0.0
ADD . /var/www/html

EXPOSE 80
# docker build -t edumar111/php-online:1.0.0 -f Dockerfile .
# docker push     edumar111/php-online:1.0.0
# docker run -d --name php-online -p 80:80  edumar111/php-online:1.0.0

#http://localhost/index.php
#http://localhost/index/crea/index.php